local Library = loadstring(Game:HttpGet('https://raw.githubusercontent.com/NoobHubV1/NoobHubV1/main/Wizard%20Lib.lua'))()
local Window = Library:NewWindow("Merge Brainrot")
local Rstorage = game.ReplicatedStorage
local Main = Window:NewSection("Main")
Main:CreateTextbox("Add Cash", function(value)
     Rstorage.Remotes.AddValueEvent:FireServer("Cash", tonumber(value))
end)
Main:CreateTextbox("Add Gem", function(value)
     Rstorage.Remotes.GemEvent:FireServer(tonumber(value))
end)
Main:CreateButton("Unlock All Brainrot", function()
     Rstorage.Remotes.UpdateBestBlockEvent:FireServer(100)
end)
Main:CreateButton("100K Max Pets", function()
     Rstorage.Remotes.MultiplierEvent:FireServer("MaxPets", 100000)
end)
Main:CreateButton("10K Max Block", function()
     Rstorage.Remotes.UpgradeEvent:FireServer("MaxBlocksLevel", 10000, 0)
end)
Main:CreateButton("1qd Cash Multiplier", function()
     Rstorage.Remotes.MultiplierEvent:FireServer("CashMultiplier", 1e15)
end)
Main:CreateButton("10K Spawn Rate Level", function()
     Rstorage.Remotes.UpgradeEvent:FireServer("SpawnRateLevel", 10000, 0)
end)
Main:CreateButton("100K Lucky Merge Level", function()
     Rstorage.Remotes.UpgradeEvent:FireServer("LuckyMergeLevel", 100000, 0)
end)
Main:CreateButton("10K Auto Merge Level", function()
     Rstorage.Remotes.UpgradeEvent:FireServer("AutoMergeLevel", 10000, 0)
end)
Main:CreateButton("10K Cash Rate Level", function()
     Rstorage.Remotes.UpgradeEvent:FireServer("CashRateLevel", 10000, 0)
end)
Main:CreateButton("100 Spawn Tier Level", function()
     Rstorage.Remotes.UpgradeEvent:FireServer("SpawnTierLevel", 100, 0)
end)
